travis:
  secure:
    BINSTAR_TOKEN: sxB+jesg7evLoOtT7bkwltABowlOV4B+lmsnugwbFdnihGij5fd6DiM6pIwxHWl+sNBD84ufERDV2wD6NW9bMXwj7pbgS9lTzHLQY3iOIIqO1TJW4a1lp46FsLpTMQiwj7m6r6SAePDoRIuc7csm4ndOURuRoAgsL/pzteSI40wqsDVmZWqfE/RslEc+eXxrpa0KrskprEriMhnRw8UmkkmMsQB5Pv5VgHTozEZirTGYrFGHCGf2bBfKf5saz5yXLWilD/JhjaFqAKDgeVL848EHo8VAvaGOb8Ph0WC79nr+mGlDVzhCBPm6k9o4rFqtxkw3e33hEWKI22PVzA0/AvKL60/Uij3QSaKGr+8JeTuu11EumFyaIaJ+AXhOAtLqSR3Pb28+YZKi0oSFi/IdZEE3o6SqftAdswRANsS6gBJenZwSZK8q9MFTOZMD4Tt1qHtAr2N3bVRg34PiRaq9Nls53uISdd6IpichmRveeZHT2myvNievFaOGu3+sh8NQs6kPmjffMaG1Zc7exP+4tiAzP2PEVOZuxTo4sdaUOYh7OHWwDMqC4c56DTV3ONnZOOr/yp8pOO1Of0PRMggsNn2ifA7dg9K4KCPbK/5YNl8731Q4CCXm4NnVLBaVNT8OVj4SmyiHqJ59EAq320WPWGFRn2l1QmazhmKeEY1NdFo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
