travis:
  secure:
    BINSTAR_TOKEN: jIFiKLdvf4EVEFBsWXZNEh6pL7UU/+tRVYm134ntzk/cYOSedGSTLKSmVlol1hkP0ofNVtK7K0N797REswgvb6hGdNabdDaHOrO7xJOcyWR1F/bY9I/A5eKAxNniKVseXaWiqfqNd002khQ1m45XXTEBN2V+t4kHhHLf6uMZiRzTa4J775fv7uuSRKLbvTnwCdrKNn9KQnvQd5lcVXwbT/qaiMBqkKzK9jaSlKjygl7jc6b6hBEBSsJW9Q2rHFS2TkuxXMUcWfFNKr4xeP+4PACS/SIKFpNPf2z/7a6caFZ65rcN5UXuMjudUiRY+L2efe9iscU37kipKn+B1g3oeL0uo/cxAQ/gclhJKE97biPRNsu373tSxCfUyKJzJh4YEabboI0oZiIPuskd1T9+quhaboBnL9Ius2erj+XyCQW10l+aOa0KTJKvqgq3jqrIJVEGbicDnU2s3kkUAs2ZHQoRnXfCYShJiNQAWLlHNJmhlLRIEOsbSaUu3mAaprRtee7TCGGNvg4qAhomHEh/vQjLy7Ymj0qWLDpobbuNCvEIIo/2VAMp4RPzchvz/hwI7xAcXn4nTrUZ8iN9KlG9DVyzxYxtbw6JsRlIz3ayDwCr7ePeQqU3ycRIjUuafxrd6lyhZGmSTxbpglD5bNvKxBafQQBDeTiLwQAcNgzc+Yg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
